Repository wireapp/wire-ios-data-model, pull requests merged in 2018-10, with the labels that each got.

#564 Feature/mentions open notification
  Source/Model/Conversation/ZMConversation+Timestamps.swift
  Tests/Source/Model/Conversation/ZMConversationTests+Timestamps.swift
Labels: Minor changes

#567 Include self mentions in badge calculations
  Resources/zmessaging.xcdatamodeld/.xccurrentversion
  Resources/zmessaging.xcdatamodeld/zmessaging2.55.0.xcdatamodel/contents
  Source/Model/Conversation/ZMConversation+Internal.h
  Source/Model/Conversation/ZMConversation+Mute.swift
  Source/Model/Conversation/ZMConversation+Timestamps.swift
  Source/Model/Conversation/ZMConversation+UnreadCount.h
  Source/Model/Conversation/ZMConversation+UnreadCount.m
  Source/Model/Conversation/ZMConversation.m
  Source/Public/ZMConversation.h
  Tests/Resources/store2-54-0.wiredatabase
  Tests/Source/ManagedObjectContext/DatabaseMigrationTests.swift
  Tests/Source/Model/Conversation/ZMConversationTests+Timestamps.swift
  Tests/Source/Model/Conversation/ZMConversationTests.m
  Tests/Source/Model/ZMBaseManagedObjectTest.h
  Tests/Source/Model/ZMBaseManagedObjectTest.m
  WireDataModel.xcodeproj/project.pbxproj
Labels: API breaker

#580 Add method for computing a hash of the message content
  Cartfile.resolved
  Source/Model/Message/ZMAssetClientMessage.swift
  Source/Model/Message/ZMClientMessage.m
  Source/Model/Message/ZMOTRMessage+ContentHashing.swift
  Source/Utilis/Protos/ZMGenericMessage+Hashing.swift
  Source/Utilis/Protos/ZMGenericMessage+Helper.swift
  Tests/Source/Utils/ZMGenericMessageTests+Hashing.swift
  WireDataModel.xcodeproj/project.pbxproj
Labels: DO NOT MERGE, Minor changes

#583 [WIP] Process replies when inserting new messages
  Cartfile.resolved
  Source/Model/Message/ZMClientMessage+TextMessageData.swift
  Source/Model/Message/ZMMessage+Internal.h
  Source/Model/Message/ZMMessage.m
  Source/Model/Validation/PBMessage+Validation.swift
  Source/Public/ZMMessage.h
  Source/Utilis/Protos/ZMGenericMessage+Helper.swift
  Tests/Source/ManagedObjectContext/ZMSyncMergePolicyTests.m
  Tests/Source/Model/Conversation/ZMConversationTests.m
  Tests/Source/Model/Messages/ZMClientMessageTests+Editing.m
  Tests/Source/Model/Messages/ZMClientMessageTests.m
  Tests/Source/Model/Messages/ZMClientMessagesTests+Replies.swift
  Tests/Source/Model/Messages/ZMMessageTests.m
  Tests/Source/Model/ZMBaseManagedObjectTest.m
  WireDataModel.xcodeproj/project.pbxproj
Labels: DO NOT MERGE
