Repository wireapp/wire-ios-data-model, pull requests merged in 2019-06, with the labels that each got.

#737 ZIOS-11474: Persist legal hold request
  Cartfile
  Cartfile.resolved
  Resources/zmessaging.xcdatamodeld/.xccurrentversion
  Resources/zmessaging.xcdatamodeld/zmessaging2.73.0.xcdatamodel/contents
  Source/Model/User/UserType.swift
  Source/Model/User/ZMSearchUser.swift
  Source/Model/User/ZMUser+Internal.h
  Source/Model/User/ZMUser+LegalHoldRequest.swift
  Source/Model/User/ZMUser.m
  Source/Model/UserClient/UserClient.swift
  Source/Notifications/ObjectObserverTokens/UserChangeInfo.swift
  Tests/Resources/store2-73-0.wiredatabase
  Tests/Source/ManagedObjectContext/DatabaseMigrationTests.swift
  Tests/Source/Model/Observer/UserObserverTests.swift
  Tests/Source/Model/User/ZMUserLegalHoldTests.swift
  WireDataModel.xcodeproj/project.pbxproj
Labels: DO NOT MERGE

#743 Fix legal hold disclosure issues
  Source/Model/Conversation/ZMConversation+Internal.h
  Source/Model/Conversation/ZMConversation+SecurityLevel.swift
  Source/Model/Conversation/ZMConversation+SystemMessages.swift
  Source/Model/Conversation/ZMConversation+Transport.m
  Source/Model/Conversation/ZMConversation.m
  Source/Model/User/ZMUser+LegalHoldRequest.swift
  Source/Model/User/ZMUser.swift
  Source/Model/UserClient/UserClient.swift
  Tests/Source/Model/Conversation/ZMConversationTests+Legalhold.swift
  Tests/Source/Model/Conversation/ZMConversationTests+SecurityLevel.m
  Tests/Source/Model/Conversation/ZMConversationTests+participants.m
  Tests/Source/Model/Conversation/ZMConversationTests.m
  Tests/Source/Model/Messages/ZMAssetClientMessageTests.swift
  Tests/Source/Model/Messages/ZMClientMessageTests+OTR.swift
  Tests/Source/Model/Observer/ConversationObserverTests.swift
  Tests/Source/Model/User/ZMUserLegalHoldTests.swift
  Tests/Source/Utils/DuplicatedEntityRemovalTests.swift
Labels: API breaker

#744 ZIOS-11499: Fix redundant legal hold update messages
  Source/Model/Conversation/ZMConversation+SecurityLevel.swift
  Tests/Source/Model/Conversation/ZMConversationTests+Legalhold.swift
Labels: API breaker

#745 Support for cancelling legal hold request
  Source/Model/User/ZMUser+LegalHoldRequest.swift
  Tests/Source/Model/User/ZMUserLegalHoldTests.swift
Labels: API breaker

#746 Add method to verify legal hold subjects in a conversation
  Source/Model/Conversation/ZMConversation+SecurityLevel.swift
  Source/Model/User/ZMUser.swift
  Source/Notifications/ObjectObserverTokens/UserChangeInfo.swift
  Tests/Source/Model/Conversation/ZMConversationTests+Legalhold.swift
  Tests/Source/Model/Observer/UserObserverTests.swift
Labels: Minor changes
