Repository wireapp/wire-ios-data-model, pull requests merged in 2020-04, with the labels that each got.

#965 [Fix] Edit Message Not Applied
  Source/Model/Message/ZMClientMessage+TextMessageData.swift
Labels: Patch changes

#974 [Fix] Don't add deleted participants to conversation
  Source/Model/Conversation/ZMConversation+Participants.swift
  Tests/Source/Model/Conversation/ZMConversationTests+Participants.swift
Labels: Minor changes

#975 [Fix] Don't update name for deleted users
  Source/Model/User/ZMUser.m
  Tests/Source/Model/User/ZMUserTests.m
Labels: Minor changes

#871 [Chore] Migrate to Xcode 11.3
  Cartfile
  Cartfile.private
  Cartfile.resolved
  Resources/Configurations/zmc-config/project-common.xcconfig
  Tests/Source/ManagedObjectContext/DatabaseMigrationTests.swift
  Tests/Source/Model/Conversation/ZMConversationTests+Messages.swift
  WireDataModel.xcodeproj/project.pbxproj
  WireDataModel.xcodeproj/xcshareddata/xcschemes/WireDataModel.xcscheme
Labels: DO NOT MERGE
