Repository wireapp/wire-ios-data-model, pull requests merged in 2020-01, with the labels that each got.

#865 Fix: migration to roles failing due to duplicate Roles being inserted
  Source/Model/Conversation/ZMConversation+Patches.swift
  Tests/Source/Utils/SelfUserParticipantMigrationTests.swift
Labels: Patch changes

#868 [Fix] Remove markedForInsertion, markedForDeletion from Role
  Resources/zmessaging.xcdatamodeld/.xccurrentversion
  Resources/zmessaging.xcdatamodeld/zmessaging2.79.0.xcdatamodel/contents
  Source/Model/Conversation/ZMConversation+Participants.swift
  Source/Model/ConversationRole/ParticipantRole.swift
  Source/Model/User/ZMUser.swift
  Source/Model/UserClient/UserClient.swift
  Source/Notifications/ObjectObserverTokens/ParticipantRoleChangeInfo.swift
  Source/Notifications/SideEffectSources.swift
  Tests/Resources/store2-79-0.wiredatabase
  Tests/Source/ManagedObjectContext/DatabaseMigrationTests.swift
  Tests/Source/Model/Conversation/ParticipantRoleTests.swift
  Tests/Source/Model/Conversation/ZMConversationTests+Participants.swift
  Tests/Source/Model/Observer/ConversationObserverTests.swift
  Tests/Source/Model/Observer/ObjectObserverToken/ParticipantRoleObserverTests.swift
  WireDataModel.xcodeproj/project.pbxproj
Labels: API breaker

#867 [Chore] Remove deprecated method
  Source/Model/Conversation/ZMConversation+Predicates.swift
Labels: API breaker

#869 [Fix] Extend UserType
  Source/Model/User/UserType+ZMUser.swift
  Source/Model/User/UserType.swift
  Source/Model/User/ZMSearchUser.swift
  Source/Model/User/ZMUser+Permissions.swift
  Tests/Source/Model/Observer/ConversationObserverTests.swift
  Tests/Source/Model/User/ZMUserTests+Permissions.swift
  WireDataModel.xcodeproj/project.pbxproj
Labels: API breaker

#873 [Refactor] Send regular messages using Swift Protobuf API
  Source/Model/Conversation/ZMConversation+Message.swift
  Source/Model/Conversation/ZMConversation.m
  Source/Model/Message/ZMAssetClientMessage.swift
  Source/Model/Message/ZMFileMetadata.swift
  Source/Utilis/Protos/GenericMessage+Helper.swift
Labels: Patch changes

#876 [Fix] Update UserType to hide Role
  Source/Model/User/UserType+ConversationRoles.swift
  Source/Model/User/UserType.swift
  Source/Model/User/ZMSearchUser.swift
  Source/Model/User/ZMUser.swift
  WireDataModel.xcodeproj/project.pbxproj
Labels: API breaker

#878 [Fix] image quotes are getting lost
  Source/Model/Conversation/ZMConversation+Message.swift
  Source/Utilis/Protos/GenericMessage+Helper.swift
  Tests/Source/Model/Conversation/ZMConversationTests+Messages.swift
Labels: Patch changes

#879 Refactor/Migrate protobuf invisible messages
  Source/Model/Conversation/ZMConversation+Internal.h
  Source/Model/Conversation/ZMConversation+Message.swift
  Source/Model/Conversation/ZMConversation.m
  Source/Model/Message/ConversationMessage+Reaction.swift
  Source/Utilis/Protos/GenericMessage+Helper.swift
Labels: Patch changes

#881 [Refactor] Hide Concrete Users in User Classes
  Source/Notifications/ObjectObserverTokens/UserChangeInfo.swift
  Tests/Source/Model/Observer/NotificationDispatcherTests.swift
  Tests/Source/Model/Observer/SearchUserObserverTests.swift
  Tests/Source/Model/Observer/UserObserverTests.swift
Labels: API breaker

#886 [Refactor] Swift protobuf - LinkPreview
  Source/Model/Conversation/ZMConversation+Message.swift
  Source/Utilis/Protos/GenericMessage+Helper.swift
  Tests/Source/Utils/GenericMessageTests+LinkMetaData.swift
  WireDataModel.xcodeproj/project.pbxproj
Labels: Minor changes

#887 [Refactor] Edit messages using Swift Protobuf API
  Source/Model/Message/ZMClientMessage+TextMessageData.swift
  Source/Utilis/Protos/GenericMessage+Helper.swift
Labels: Patch changes
