Repository wireapp/wire-ios-data-model, pull requests merged in 2020-03, with the labels that each got.

#904 [Refactor] Add method to determine if user type is sender
  Source/Model/Message/ConversationMessage.swift
Labels: Minor changes

#903 [Fix] Improve logging when removing participants from a group
  Source/Model/Conversation/ZMConversation+SecurityLevel.swift
  Source/Model/Conversation/ZMConversation+Transport.swift
Labels: Patch changes

#908 [Refactor] Use UserType in publicly exposed methods
  Source/Model/Conversation/ZMConversation+Creation.swift
Labels: API breaker

#905 [Fix] Retain cycle in ConversationListObserverProxy
  Cartfile
  Cartfile.resolved
  Source/ConversationList/ConversationDirectory.swift
Labels: API breaker

#918 [Fix]Unable to get correct device class on iPad
  Source/Model/UserClient/UserClient.swift
Labels: Patch changes

#916 Feature/alarming response
  Cartfile
  Cartfile.resolved
  Resources/zmessaging.xcdatamodeld/.xccurrentversion
  Resources/zmessaging.xcdatamodeld/zmessaging2.80.0.xcdatamodel/contents
  Source/Model/ButtonState/ButtonState.swift
  Source/Model/Conversation/ZMConversation+Message.swift
  Source/Model/Message/Composite/CompositeMessageData.swift
  Source/Model/Message/Composite/CompositeMessageItemContent.swift
  Source/Model/Message/ConversationMessage.swift
  Source/Model/Message/Mention.swift
  Source/Model/Message/Message.swift
  Source/Model/Message/ZMClientMessage+Composite.swift
  Source/Model/Message/ZMClientMessage+Encryption.swift
  Source/Model/Message/ZMClientMessage+TextMessageData.swift
  Source/Model/Message/ZMClientMessage.m
  Source/Model/Message/ZMMessage.m
  Source/Model/Message/ZMOTRMessage.h
  Source/Model/Message/ZMOTRMessage.m
  Source/Notifications/DependencyKeyStore.swift
  Source/Notifications/ObjectObserverTokens/MessageChangeInfo.swift
  Source/Notifications/SideEffectSources.swift
  Source/Utilis/Protos/GenericMessage+Helper.swift
  Source/Utilis/Protos/ZMGenericMessage+Utils.m
  Tests/Resources/store2-80-0.wiredatabase
  Tests/Source/ManagedObjectContext/DatabaseMigrationTests.swift
  Tests/Source/Model/Conversation/ZMConversationTests+Messages.swift
  Tests/Source/Model/Messages/MentionTests.swift
  Tests/Source/Model/Messages/ZMClientMessageTests+Composite.swift
  WireDataModel.xcodeproj/project.pbxproj
Labels: Feature request
