Repository wireapp/wire-ios-data-model, pull requests merged in 2021-11, with the labels that each got.

#1259 Fix: App crashes in [ZMConversation refreshObjectsThatAreNotNeededInSyncContext:self]
  Source/Model/Conversation/ZMConversation+Participants.swift
  Source/Model/ConversationRole/ParticipantRole.swift
  Source/Model/User/ZMUser+Availability.swift
  Tests/Source/Model/Conversation/ZMConversationTests+SecurityLevel.swift
  Tests/Source/Model/Conversation/ZMConversationTests+Transport.swift
  Tests/Source/Utils/SelfUserParticipantMigrationTests.swift
Labels: API breaker

#1232 [Feature] Self-deleting message config
  Source/Model/Conversation/ConversationLike.swift
  Source/Model/Conversation/SelfDeletingMessages/MessageDestructionTimeoutType.swift
  Source/Model/Conversation/SelfDeletingMessages/MessageDestructionTimeoutValue.swift
  Source/Model/Conversation/SelfDeletingMessages/ZMConversation+SelfDeletingMessages.swift
  Source/Model/Conversation/ZMConversation+Ephemeral.swift
  Source/Model/Conversation/ZMConversation+Message.swift
  Source/Model/Conversation/ZMConversation+SystemMessages.swift
  Source/Model/Conversation/ZMConversation+Transport.swift
  Source/Model/FeatureConfig/Feature.swift
  Source/Model/FeatureConfig/FeatureService.swift
  Source/Model/FeatureConfig/SelfDeletingMessages/Feature.SelfDeletingMessages.swift
  Source/Model/Message/ZMAssetClientMessage.swift
  Source/Model/Message/ZMClientMessage+LinkPreview.swift
  Source/Utilis/Protos/GenericMessage+Helper.swift
  Tests/Source/Model/Conversation/ZMConversationTests+Ephemeral.swift
  Tests/Source/Model/Conversation/ZMConversationTests+Messages.swift
  Tests/Source/Model/FeatureConfiguration/FeatureTests.swift
  Tests/Source/Model/Messages/GenericMessageTests+LegalHoldStatus.swift
  Tests/Source/Model/Messages/ZMAssetClientMessageTests+Ephemeral.swift
  Tests/Source/Model/Messages/ZMClientMessageTests+Deletion.swift
  Tests/Source/Model/Messages/ZMClientMessageTests+Ephemeral.swift
  Tests/Source/Model/Messages/ZMClientMessageTests+OTR.swift
  Tests/Source/Model/Messages/ZMClientMessageTests.swift
  Tests/Source/Model/Messages/ZMMessageCategorizationTests.swift
  Tests/Source/Model/Observer/ConversationObserverTests.swift
  Tests/Source/Model/TextSearchQueryTests.swift
  Tests/Source/Model/Utils/GenericMessageTests+Obfuscation.swift
  Tests/Source/Model/Utils/ProtobufUtilitiesTests.swift
  Tests/Source/Model/Utils/ProtosTests.swift
  Tests/Source/Utils/GenericMessageTests+Hashing.swift
  WireDataModel.xcodeproj/project.pbxproj
Labels: API breaker

#1272 [Fix] App crashes after update
  Source/ManagedObjectContext/CoreDataStack.swift
Labels: Patch changes

#1276 [Chore] Add public logs
  Patches/InvalidConversationRemoval.swift
  Source/ManagedObjectContext/CoreDataStack.swift
  Source/Model/FeatureConfig/Feature.swift
Labels: Patch changes

#1277 [Fix] Remove forced unwrapping
  Source/Model/FeatureConfig/FeatureService.swift
Labels: Patch changes

#1285 fix: Deletion rule for participantRoles SQCORE-1178
  Resources/zmessaging.xcdatamodeld/.xccurrentversion
  Resources/zmessaging.xcdatamodeld/zmessaging2.97.0.xcdatamodel/contents
  Tests/Resources/store2-97-0.wiredatabase
  Tests/Source/ManagedObjectContext/DatabaseMigrationTests.swift
  WireDataModel.xcodeproj/project.pbxproj
Labels: Patch changes

#1281 revert: Self-deleting messages SQSERVICES-1018
  Patches/InvalidConversationRemoval.swift
  Source/Model/Conversation/ConversationLike.swift
  Source/Model/Conversation/SelfDeletingMessages/MessageDestructionTimeoutType.swift
  Source/Model/Conversation/SelfDeletingMessages/MessageDestructionTimeoutValue.swift
  Source/Model/Conversation/SelfDeletingMessages/ZMConversation+SelfDeletingMessages.swift
  Source/Model/Conversation/ZMConversation+Ephemeral.swift
  Source/Model/Conversation/ZMConversation+Message.swift
  Source/Model/Conversation/ZMConversation+SystemMessages.swift
  Source/Model/Conversation/ZMConversation+Transport.swift
  Source/Model/FeatureConfig/Feature.swift
  Source/Model/FeatureConfig/FeatureService.swift
  Source/Model/FeatureConfig/SelfDeletingMessages/Feature.SelfDeletingMessages.swift
  Source/Model/Message/ZMAssetClientMessage.swift
  Source/Model/Message/ZMClientMessage+LinkPreview.swift
  Source/Utilis/Protos/GenericMessage+Helper.swift
  Tests/Source/Model/Conversation/ZMConversationTests+Ephemeral.swift
  Tests/Source/Model/Conversation/ZMConversationTests+Messages.swift
  Tests/Source/Model/FeatureConfiguration/FeatureTests.swift
  Tests/Source/Model/Messages/GenericMessageTests+LegalHoldStatus.swift
  Tests/Source/Model/Messages/ZMAssetClientMessageTests+Ephemeral.swift
  Tests/Source/Model/Messages/ZMClientMessageTests+Deletion.swift
  Tests/Source/Model/Messages/ZMClientMessageTests+Ephemeral.swift
  Tests/Source/Model/Messages/ZMClientMessageTests+OTR.swift
  Tests/Source/Model/Messages/ZMClientMessageTests.swift
  Tests/Source/Model/Messages/ZMMessageCategorizationTests.swift
  Tests/Source/Model/Observer/ConversationObserverTests.swift
  Tests/Source/Model/TextSearchQueryTests.swift
  Tests/Source/Model/Utils/GenericMessageTests+Obfuscation.swift
  Tests/Source/Model/Utils/ProtobufUtilitiesTests.swift
  Tests/Source/Model/Utils/ProtosTests.swift
  Tests/Source/Utils/GenericMessageTests+Hashing.swift
  WireDataModel.xcodeproj/project.pbxproj
Labels: chore

#1291 fix: use private class for fetching framework bundle SQSERVICES-1031
  Patches/PersistedDataPatches.swift
Labels: Patch changes

#1292 fix: fetch bundle with bundle identifier SQSERVICES-1031
  Patches/PersistedDataPatches.swift
  Resources/Configurations/version.xcconfig
Labels: Patch changes

#1269 feat: check domain when checking if users are on the same team FS-35
  Source/Model/User/ZMUser+Permissions.swift
  Tests/Source/Model/User/ZMUserTests+Permissions.swift
Labels: Minor changes
