Repository wireapp/wire-ios-data-model, pull requests merged in 2021-01, with the labels that each got.

#1097 [Fix] Send confirmation receipts to composite messages
  Source/Model/Conversation/ZMConversation+Timestamps.swift
  Source/Model/Conversation/ZMConversation.m
  Source/Model/Message/ZMOTRMessage+Confirmations.swift
  Tests/Source/Model/Conversation/ZMConversationTests+UnreadMessages.swift
  Tests/Source/Model/Conversation/ZMConversationTests.m
  Tests/Source/Model/Messages/ZMMessageTests+Confirmation.swift
Labels: Patch changes

#1110 [Revert] Preventing last read update for updated messages
  Source/Model/Conversation/ZMConversation+Timestamps.swift
  Tests/Source/Model/Conversation/ZMConversationTests+UnreadMessages.swift
Labels: Patch changes

#1111 [Fix] Read receipts not sent for some messages
  Source/Model/Conversation/ZMConversation+Confirmations.swift
  Source/Model/Conversation/ZMConversation+Internal.h
  Source/Model/Conversation/ZMConversation+Timestamps.swift
  Source/Model/Conversation/ZMConversation.m
  Tests/Source/Model/Conversation/ZMConversationTests+Confirmations.swift
Labels: Minor changes

#1115 [Fix] App lock passcode migration
  Patches/TransferApplockKeychain.swift
  Tests/Source/Utils/TransferApplockKeychainTests.swift
Labels: Patch changes

#1114 Fix: replace UserType properties with ZMConversation parameter to ConversationLike protocol
  Source/Model/Conversation/ConversationLike.swift
  Source/Model/User/UserType.swift
  Source/Model/User/ZMSearchUser.swift
  Source/Model/User/ZMUser+Permissions.swift
  Source/Model/User/ZMUser+Teams.swift
  Source/Model/User/ZMUser.swift
  WireDataModel.xcodeproj/project.pbxproj
Labels: API breaker

#1119 [Refactor] Delete Team.update(with:) which is now unused
  Source/Model/Conversation/Team+Transport.swift
  Tests/Source/Model/Messages/FileAssetCacheTests.swift
  Tests/Source/Model/TeamTests.swift
  WireDataModel.xcodeproj/project.pbxproj
Labels: API breaker

#1127 [Fix] Existing system message changing type due to changed enum order
  Source/Public/ZMMessage.h
Labels: Patch changes

#1126 Move Conversation properties to ConversationLike
  Source/Model/Conversation/ConversationLike.swift
  Source/Model/Conversation/ZMConversation+AccessMode.swift
  Source/Model/Message/ConversationMessage.swift
  Tests/Source/Model/CoreDataRelationshipsTests.m
Labels: API breaker

#1125 Add conversationLike property to ZMConversationMessage and change usersReaction's type
  Source/Model/Conversation/ConversationLike.swift
  Source/Model/Conversation/ZMConversation+AccessMode.swift
  Source/Model/Message/ConversationMessage.swift
  Tests/Source/Model/CoreDataRelationshipsTests.m
Labels: API breaker

#1128 Add quoteMessage to ZMTextMessageData
  Source/Model/Message/Composite/CompositeMessageItemContent.swift
  Source/Model/Message/ZMClientMessage+TextMessageData.swift
  Source/Public/ZMMessage.h
  Tests/Source/Model/Conversation/ZMConversationTests+Messages.swift
  Tests/Source/Model/Messages/ZMClientMessageTests+Editing.swift
  Tests/Source/Model/Messages/ZMClientMessageTests+Replies.swift
Labels: API breaker
