Repository wireapp/wire-ios-data-model, pull requests merged in 2021-07, with the labels that each got.

#1174 Feature: xcframework
  Cartfile
  Cartfile.private
  Cartfile.resolved
  Resources/Configurations/WireDataModel.xcconfig
  Resources/Configurations/zmc-config/ios-test-host.xcconfig
  Resources/Configurations/zmc-config/ios-test-target.xcconfig
  Resources/Configurations/zmc-config/ios.xcconfig
  Resources/Configurations/zmc-config/project-common.xcconfig
  Source/Model/Message/ZMSystemMessage+ChildMessages.swift
  Tests/Source/Model/Messages/ZMMessageTests.m
  WireDataModel.xcodeproj/project.pbxproj
Labels: DO NOT MERGE

#1182 [Feature] Add file sharing feature
  Source/Model/FeatureConfig/Feature.swift
  Source/Model/FeatureConfig/FeatureService.swift
  Source/Model/FeatureConfig/FileSharing/Feature.FileSharing.swift
  WireDataModel.xcodeproj/project.pbxproj
Labels: Feature request

#1183 [Refactor] Feature configs
  Resources/zmessaging.xcdatamodeld/.xccurrentversion
  Resources/zmessaging.xcdatamodeld/zmessaging2.93.0.xcdatamodel/contents
  Source/ManagedObjectContext/CoreDataStack.swift
  Source/Model/Conversation/Team+Feature.swift
  Source/Model/FeatureConfig/AppLock/AppLockController.Config.swift
  Source/Model/FeatureConfig/AppLock/AppLockController.swift
  Source/Model/FeatureConfig/AppLock/Feature.AppLock.swift
  Source/Model/FeatureConfig/Feature.swift
  Source/Model/FeatureConfig/FeatureLike.swift
  Source/Model/FeatureConfig/FeatureService.swift
  Tests/Resources/store2-93-0.wiredatabase
  Tests/Source/ManagedObjectContext/DatabaseMigrationTests.swift
  Tests/Source/Model/FeatureConfiguration/AppLock/AppLockControllerTests.swift
  Tests/Source/Model/FeatureConfiguration/FeatureLikeTests.swift
  Tests/Source/Model/FeatureConfiguration/FeatureServiceTests.swift
  Tests/Source/Model/FeatureConfiguration/FeatureTests.swift
  Tests/Source/Model/TeamTests.swift
  Tests/Source/Utils/InvalidFeatureRemovalTests.swift
  Tests/Source/Utils/TransferApplockKeychainTests.swift
  WireDataModel.xcodeproj/project.pbxproj
Labels: API breaker
