Repository wireapp/wire-ios-data-model, pull requests merged in 2022-02, with the labels that each got.

#1339 chore: release new version
  Resources/Configurations/version.xcconfig
  Source/Model/DuplicateMerging.swift
Labels: Patch changes

#1322 feat: Separate Access Controls for Guests And Services SQSERVICES-1052
  Patches/PersistedDataPatches+Directory.swift
  Resources/zmessaging.xcdatamodeld/.xccurrentversion
  Resources/zmessaging.xcdatamodeld/zmessaging2.98.0.xcdatamodel/contents
  Source/Model/Conversation/ConversationLike.swift
  Source/Model/Conversation/ZMConversation+AccessMode.swift
  Source/Model/Conversation/ZMConversation+Creation.swift
  Source/Model/Conversation/ZMConversation+Patches.swift
  Source/Model/Conversation/ZMConversation+Transport.swift
  Source/Model/Conversation/ZMConversation.m
  Source/Notifications/ObjectObserverTokens/ConversationChangeInfo.swift
  Tests/Resources/store2-98-0.wiredatabase
  Tests/Source/ManagedObjectContext/DatabaseMigrationTests.swift
  Tests/Source/Model/Conversation/ZMConversationTests+AccessMode.swift
  Tests/Source/Model/Conversation/ZMConversationTests+Transport.swift
  Tests/Source/Model/Conversation/ZMConversationTests+gapsAndWindows.m
  Tests/Source/Model/Conversation/ZMConversationTests.m
  Tests/Source/Model/Observer/ConversationObserverTests.swift
  Tests/Source/Utils/AccessRoleMigrationTests.swift
  Tests/Source/Utils/RolesMigrationTests.swift
  WireDataModel.xcodeproj/project.pbxproj
Labels: DO NOT MERGE

#1334 feat: add support for classified domains FS-96
  Source/Model/FeatureConfig/ClassifiedDomains/Feature+ClassifiedDomains.swift
  Source/Model/FeatureConfig/Feature.swift
  Source/Model/FeatureConfig/FeatureService.swift
  WireDataModel.xcodeproj/project.pbxproj
Labels: API breaker
